# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20160325_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='file_type',
        ),
        migrations.AddField(
            model_name='Images',
            name='image_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
